name: classical_music_puzzle
description: A new form to enjoy classical music.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  universal_platform: ^1.0.0+1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  assets_audio_player: ^3.0.4+1
  vibration: ^1.7.4-nullsafety.0
  flutter_svg: ^1.0.3
  sensors_plus: ^1.3.0
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  generate: true

  assets:
    - assets/fonts/
    - assets/fonts/Open_Sans/
    - assets/fonts/Times_New_Roman/
    - assets/icons/
    - assets/images/
    - assets/languages/
    - assets/sounds/
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/Open_Sans_Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Open_Sans/Open_Sans_Light_Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Open_Sans/Open_Sans_Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Open_Sans/Open_Sans_Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Open_Sans/Open_Sans_Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Open_Sans/Open_Sans_Medium_Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Open_Sans/Open_Sans_Semi_Bold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Open_Sans/Open_Sans_Semi_Bold_Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Open_Sans/Open_Sans_Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Open_Sans/Open_Sans_Bold_Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Open_Sans/Open_Sans_Extra_Bold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Open_Sans/Open_Sans_Extra_Bold_Italic.ttf
          style: italic
          weight: 800
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/Times_New_Roman/Times_New_Roman_Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Times_New_Roman/Times_New_Roman_Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Times_New_Roman/Times_New_Roman_Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Times_New_Roman/Times_New_Roman_Bold_Italic.ttf
          style: italic
          weight: 700